version: 0.2

env:
  variables:
    REPOSITORY_URI: 809965951169.dkr.ecr.ap-south-1.amazonaws.com/codepipeline

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven and Docker..."
      - yum install -y maven docker

  pre_build:
    commands:
      - echo "Starting Maven build..."
      - mvn clean install
      - echo "Authenticating with Amazon ECR..."
      - aws --version
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Image Tag: $IMAGE_TAG"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker images to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Build and push complete."

artifacts:
  files:
    - target/*.jar
